# Generated by Django 4.1.3 on 2022-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofileimage_delete_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Longitude'),
        ),
    ]
