# Generated by Django 4.1.2 on 2022-10-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_lauch_date_book_sinopse_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='lauch_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
